import {
  LayoutDashboard,
  Users,
  Store,
  Warehouse,
  Package,
  FolderTree,
  ShoppingCart,
  CreditCard,
  UserCircle,
  Gift,
  Ticket,
  Megaphone,
  BarChart3,
  FileText,
  Star,
  MessageSquare,
  Settings,
  RotateCcw,
  Truck,
} from "lucide-react";

export const menuItems = [
  { icon: LayoutDashboard, label: "Dashboard", path: "/dashboard" },
  { icon: Users, label: "Admin Users", path: "/admin-users" },
  { icon: Store, label: "Vendors", path: "/vendors" },
  { icon: Warehouse, label: "Inventory", path: "/inventory" },
  { icon: Package, label: "Products", path: "/products" },
  { icon: FolderTree, label: "Categories", path: "/categories" },
  { icon: ShoppingCart, label: "Orders", path: "/orders" },
  { icon: RotateCcw, label: "Returns & Refunds", path: "/returns" },
  { icon: Truck, label: "Delivery Status", path: "/delivery" },
  { icon: CreditCard, label: "Payments", path: "/payments" },
  { icon: UserCircle, label: "Customers", path: "/customers" },
  { icon: Gift, label: "Referral System", path: "/referrals" },
  { icon: Gift, label: "Referrers", path: "/referrers" },
  { icon: Ticket, label: "Coupons", path: "/coupons" },
  { icon: Megaphone, label: "Marketing", path: "/marketing" },
  { icon: BarChart3, label: "Reports", path: "/reports" },
  { icon: FileText, label: "CMS", path: "/cms" },
  { icon: Star, label: "Reviews", path: "/reviews" },
  { icon: MessageSquare, label: "Support", path: "/support" },
  { icon: Settings, label: "Settings", path: "/settings" },
];